// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Experience struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	YearBegin   string   `json:"yearBegin"`
	YearEnd     string   `json:"yearEnd"`
	Description string   `json:"description"`
	PointList   []string `json:"pointList"`
}

type NewExperience struct {
	InputID          string   `json:"inputID"`
	InputTitle       string   `json:"inputTitle"`
	InputYearBegin   string   `json:"inputYearBegin"`
	InputYearEnd     string   `json:"inputYearEnd"`
	InputDescription string   `json:"inputDescription"`
	InputPointList   []string `json:"inputPointList"`
}

type InputDeleteExperience struct {
	InputID string `json:"inputID"`
}
